import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import PageHeader from "@/app/components/page-header";
import PageFooter from "@/app/components/page-footer";
import { ModalProvider } from "@/app/components/modal-context";
import ModalWindow from "@/app/components/modal-window";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M.Video",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProvider>
          <div className="relative">
            <PageHeader />
            {children}
            <PageFooter />
          </div>
          {/* Модальное окно подключено */}
          <ModalWindow>
            <h2 className="text-lg font-bold">Модальное окно</h2>
            <p>Контент внутри модального окна.</p>
          </ModalWindow>
        </ModalProvider>
      </body>
    </html>
  );
}
