import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import PageHeader from "@/app/components/page-header";
import PageFooter from "@/app/components/page-footer";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M.Video",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="relative">
          <PageHeader />
          {children}
          <PageFooter />
        </div>
      </body>
    </html>
  );
}
